{% set name = "freetds" %}
{% set version = "1.5.18" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.freetds.org/files/stable/{{ name }}-{{ version }}.tar.bz2
  sha256: 6b2c8b93b9ee7c83855daf745de5878790032f14dbaee553d83a9d211b84dd4b

build:
  number: 0
  run_exports:
    # Full backward compatibility so far:
    # https://abi-laboratory.pro/tracker/timeline/freetds/
    - {{ pin_subpackage('freetds') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cmake    # [win]
    - jom      # [win]
    - libtool  # [not win]
    - make     # [not win]
    - perl     # [win]
  host:
    - libiconv {{ libiconv }}  # [osx]
    - libkrb5 {{ krb5 }}       # [unix]
    - openssl {{ openssl }}
    - readline {{ readline }}  # [not win]
    - unixodbc {{ unixodbc }}  # [unix]
  run:
    - libkrb5  # [unix]
    - openssl  # exact pin handled through openssl run_exports

test:
  requires:
    # To use 'conda inspect', install conda-build
    - conda-build  # [linux or osx]
  commands:
    - tsql -C
    - conda inspect linkages freetds  # [linux or osx]
    - conda inspect objects freetds   # [osx]

about:
  home: https://www.freetds.org
  license: LGPL-2.0
  license_file: COPYING_LIB.txt
  summary: FreeTDS is a free implementation of Sybase's DB-Library, CT-Library, and ODBC libraries
  description: FreeTDS is a free implementation of Sybase's DB-Library, CT-Library, and ODBC libraries
  license_family: LGPL
  doc_url: https://www.freetds.org/docs.html
  dev_url: https://github.com/FreeTDS/freetds

extra:
  recipe-maintainers:
    - mariusvniekerk
