{% set name = 'freetds' %}
{% set version = "1.3.18" %}
{% set sha256 = "1d8561d57c71991a28f4681343785c23a6a3eb54d5bcd23897d07e3825ff2d56" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.freetds.org/files/stable/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    # https://abi-laboratory.pro/tracker/timeline/freetds/
    - {{ pin_subpackage('freetds') }}

requirements:
  build:
    - {{ compiler('c') }}
    - libtool  # [not win]
    - make   # [not win]
    - cmake  # [win]
    - jom  # [win]
    - perl  # [win]
  host:
    - openssl {{ openssl }}
    - unixodbc 2.3.11  # [unix]
    - krb5 1.20.1  # [unix]
    - readline 8.2  # [not win]
    - libiconv 1.16  # [osx]
  run:
    - krb5     # [unix]
    - openssl 3.*
    # Should be taken care of by run_exports
    # - unixodbc  # [unix]
    # - readline  # [not win]

test:
  requires:
    # To use 'conda inspect', install conda-build
    - conda-build  # [osx]
  commands:
    - tsql -C
    - conda inspect linkages freetds  # [linux or osx]
    - conda inspect objects freetds  # [osx]

about:
  home: https://www.freetds.org/
  license: LGPL-2.0
  license_file:
    - COPYING_LIB.txt
  summary: FreeTDS is a free implementation of Sybase's DB-Library, CT-Library, and ODBC libraries
  description: FreeTDS is a free implementation of Sybase's DB-Library, CT-Library, and ODBC libraries
  license_family: LGPL
  doc_url: https://www.freetds.org/docs.html
  dev_url: https://github.com/FreeTDS/freetds

extra:
  recipe-maintainers:
    - mariusvniekerk
