{% set name = "freetds" %}
{% set version = "1.5.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.freetds.org/files/stable/{{ name }}-{{ version }}.tar.bz2
  sha256: b5aa4377a669b266ff26f2d11893e65430bef377eefd92934832310774dc6942

build:
  number: 0
  run_exports:
    # https://abi-laboratory.pro/tracker/timeline/freetds/
    - {{ pin_subpackage('freetds') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cmake    # [win]
    - jom      # [win]
    - libtool  # [not win]
    - make     # [not win]
    - perl     # [win]
  host:
    - libiconv {{ libiconv }}  # [osx]
    - libkrb5 {{ krb5 }}       # [unix]
    - openssl {{ openssl }}
    - readline {{ readline }}  # [not win]
    - unixodbc {{ unixodbc }}  # [unix]
  run:
    - libkrb5  # [unix]
    - openssl  # exact pin handled through openssl run_exports
    # Should be taken care of by run_exports
    # - unixodbc  # [unix]
    # - readline  # [not win]

test:
  requires:
    # To use 'conda inspect', install conda-build
    - conda-build  # [osx]
  commands:
    - tsql -C
    - conda inspect linkages freetds  # [linux or osx]
    - conda inspect objects freetds   # [osx]

about:
  home: https://www.freetds.org
  license: LGPL-2.0
  license_file:
    - COPYING_LIB.txt
  summary: "FreeTDS is a free implementation of Sybase's DB-Library, CT-Library, and ODBC libraries"
  description: "FreeTDS is a free implementation of Sybase's DB-Library, CT-Library, and ODBC libraries"
  license_family: LGPL
  doc_url: https://www.freetds.org/docs.html
  dev_url: https://github.com/FreeTDS/freetds

extra:
  recipe-maintainers:
    - mariusvniekerk
