travis:
  secure:
    BINSTAR_TOKEN: 382cGvVYyN0MbxQla2rCoxyzSe09MKZnVwTDeZ8bqLl1mnKsCiz/S4cb2q0CCUqs+63R+M8c9U0AYErXgMn62gY7bQo/9y/QpiHovTuZs/wjiJCAN+xBRTn3xRTvBajDnbiEbbHZiURoCkizRIRZ5XWnyBzcSZuegW+VE8uV8PPAjgtxNQwlwZAm9WtHmPtNDldZ2KagUI4qTQdHgoCIqjatUbpkBdZui2cToOH2nd2Bkg/wPfVSXSI7U5/VMxuk/ZjxbsdTVZ+gWVETkSiIjQ4fXN5CXBVsXwUVoM/hh5N7l52rdIHYsJb6lV2sBzDp16yNx9DWIFlYItx9ZxBH+w+LzKpKnH4v83nBZLV9koTVrBRhPpTCil1vKzPfhOxFkwjZGpoJW/Oy7YZLIMzzmabltII3K+xuMYiTmfOYgtzznRbgcJRM/zGp3HT8Y7sVZkfGPCeG33Qn2hYSqM3YCIqLiPrd6S/FW9vMdPeGtr0bH990ZlnYB2sLih7r8KeZqTIakZve+/1DFtBZ4rnaLHbbFRNALhsdSAxyL85hjAgbF0IRX+CkphLh1r+x3DTpUzytC8benKPpjoyDDOIrwl8mbQ+Bnk76iDShd8g0xDF25P5wqMymt4gyhEtTHkHgC4a7wX0dKGOFgWiinfKfUIInzgndWW2RHlnZvNAz0vY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
