travis:
  secure:
    BINSTAR_TOKEN: Lev3nKgv2+vOZJgYDQ9UnPpC8mtcFyctA4uKtUd9jLfwWYDdBfCPIjScJ7ll8JUUDpJ61Pzzr9bwWhwS29GIOkgp8vAhXuR4D0Kf8Z30uCJBOEsuYrCgyMzA1xk1CK2GyzV68FjgSaZHrGqt1+vMqqeKqjOgwsFsB8STAzCUGp+GP5nGTxUjtonsEnNBHu4knXtmKp4Kjby+bDNwK3FgEi44yPE4LQbov9teMa6IP9Pg27QJf/H3EpOb/m3Tx2GFw4YDMRAHAVUjNw9Mdx8C1z/LnRz/S5O4B9FxgQdcDKIL7Dij5RWI1op6AgKzav+K6JdkmSr0itAB5fbfYLP1LRQnGYu8+ofXwLfnlsCAc00OrXynyfxkCmTM/5V9muUSmaBmFdOxpWJJDxCOu/JWnZFubYeHMDBq33w9Cn+N+ujkNfqsFL5K7vaWsWU1kGSdF5Llh8xH9PpzPGy8G2alkdcFeRz8A9zqiULDFrDMY5Oqo+xS+LathM0aDVzV1HgVYgVRg8HHr+MzpxVD8qqRgZ8ThjtXh4HxbulBkouBQ39JOtlYyGs8G3FYovgQ2QeXJ81PJ3OKSmIQsOHPpeqbTY5k51v7aOFQmoH9VIsPJnnsLzuEhny+Qn4lcokCl48TRwArnI74AvRckAFHP7wElbE+IDavXRQVI7R7ugoDwuA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
